### ISSUE TITLE
HLS Broadcasting is failing with HTTP 500

### ISSUE THREAD

**Issue by drexhacker** [GetStream/stream-video-flutter#611] opened 2024-03-19 12:49 UTC
Hello am trying to integrate Livestreaming with support for HLS as I would also like to display the stream on the desktop into my app but I am getting error 500 when I check the logs in the Dashboard

**Comment by deven98** [comment] 2024-03-25 15:24
Hey @drexhacker, we're looking into this for you. 

I will let you know when we have an update.

**Comment by deven98** [comment] 2024-03-26 15:35
Hey @drexhacker, the HLS stream link works on my end. Can you give me more details on what you're implementing and where you encountered the error? Any code and ways to reproduce this would be great.

**Comment by deven98** [comment] 2024-05-08 12:34
Closing this for now due to lack of details. Feel free to open this again if you experience any similar issues.

**Closed by deven98** 2024-05-08 12:34 UTC
Labels: bug

**Comment by drexhacker** [comment] 2024-05-09 02:53
@deven98 Am Very Sorry for the Late Response, I just resumed the project recently and have succeeded with HLS and Recording using the Call Type Settings in the dashboard which is much more convenient. Thank You.
